railslove/rack-tracker

- lib/rack/tracker/facebook/facebook.rb
- lib/rack/tracker/go_squared/go_squared.rb
- lib/rack/tracker/google_analytics/google_analytics.rb
- lib/rack/tracker/handler.rb
- rack-tracker.gemspec
- spec/handler/facebook_spec.rb
- spec/handler/go_squared_spec.rb
- spec/handler/google_analytics_spec.rb
- spec/spec_helper.rb
- spec/tracker/controller_spec.rb
this way they can be serialized using :json serialization and not only using :marshal.
:json is the default serializer in rails 4.1+ and considered much safer
see issue #13
> store events as hashes in the session

- README.md
- lib/rack/tracker/facebook/facebook.rb
- lib/rack/tracker/go_squared/go_squared.rb
- lib/rack/tracker/google_analytics/google_analytics.rb
- lib/rack/tracker/handler.rb
- lib/rack/tracker/handler_delegator.rb
- spec/fixtures/track_all_the_things.erb
- spec/handler/facebook_spec.rb
- spec/handler/go_squared_spec.rb
- spec/handler/google_analytics_spec.rb
- spec/tracker/controller_spec.rb
Stringify all the incomming hash keys from the `track()` methods and only work with string keys internally.
The reason is that hashes coming from the Rails session will always have string keys and this way it's consistent everwhere internally in the gem.
> Only work with stringified keys

- README.md
- lib/rack/tracker/google_analytics/google_analytics.rb
- spec/handler/google_analytics_spec.rb
This change makes it possible to set parameters such as dimension or metric see https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#customs
> google analytics: allow set parameters

- lib/rack/tracker/google_analytics/google_analytics.rb
- lib/rack/tracker/google_analytics/template/google_analytics.erb
- spec/handler/google_analytics_spec.rb
- spec/integration/google_analytics_integration_spec.rb
- requirement is needed to render events with directly javascript
- label for action is needed for https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-ecommerce#action-types
- if no attributes given don't render empty hash
> google analytics: render enhanced ecommerce requirement without any events and able to pass label for action event

- README.md
There was already a description how to use criteo, but the service was not mentioned in the list of supported services.
> Add criteo to the list of supported services

- lib/rack/tracker/google_analytics/template/google_analytics.erb
- spec/handler/google_analytics_spec.rb
When using Turbolinks, we have to require the template using `position: :body` so that the `<script>` tag will get re-evaluated between each page change.
However (as noted in #26), we have to specify the whole page URL when we send the `pageview` command because omitting it will only track the page from the original request.
> Send pageview command with whole URL

- README.md
- lib/rack/tracker/zanox/template/zanox.erb
- lib/rack/tracker/zanox/zanox.rb
- spec/handler/zanox_spec.rb
- spec/integration/zanox_integration_spec.rb
- spec/support/metal_controller.rb
Zanox has alerted me to the fact that our url path was set up wrong. This PR fixes that. Whereas before the path in the template was set as, for example, 
`https://ad.zanox.com/abc` and could not be changed, now the `abc` can be set dynamically by passing in a parameter along w/ the rest of them. 
let me know if there's any questions/concerns!
> set zanox path extension

- lib/rack/tracker/google_analytics/template/google_analytics.erb
- spec/handler/google_analytics_spec.rb
I made a mistake in my previous pull request (#40) and should not have used `{ location: '…' }`. We should be using a third `String` parameter instead, according to [this documentation article](https://developers.google.com/analytics/devguides/collection/analyticsjs/pages#overriding).
Sorry about that!
> Fix Google Analytics pageview command arguments

- README.md
- lib/rack/tracker/google_adwords_conversion/template/google_adwords_conversion.erb
- spec/handler/google_adwords_conversion_spec.rb
We'd like to be able to use options configured in our middleware for GAC
as default when we don't specify them on our controllers.
```ruby
config.middleware.use(Rack::Tracker) do
handler :google_analytics, { ecommerce: true, tracker: 'UA-XXXXXXX-X' }
handler :google_adwords_conversion, { id: 123456,
language: "en",
format: "3",
color: "ffffff",
label: "Conversion Label",
currency: "USD" }
end
def show
tracker do |t|
t.google_adwords_conversion :conversion, { value: @order.cost }
end
end
```
> Use default options from handler for GAC

- lib/rack/tracker.rb
- lib/rack/tracker/google_analytics/google_analytics.rb
- lib/rack/tracker/handler.rb
- lib/rack/tracker/javascript_helper.rb
- spec/integration/google_analytics_integration_spec.rb
- spec/support/metal_controller.rb
- spec/tracker/javascript_helper_spec.rb
I've started the implementation of a javascript escaper module took from rails code.
I've currently only implemented
* The helper itself (took from rails)
* Mixed in the helper to allow usage in erb templates
* Created a failing spec for an analytic dimension and a patch to fix it
What is still missing is to review all trackers and escape where potentially untrusted input is written.
I think this should be enough to start with.
Let me know what do you think.
> Javascript escape implementation to prevent XSS

- .travis.yml
- rack-tracker.gemspec
Updated Travis matrix to exclude Rails 5 on Ruby < 2.2, and pinned the addressable and mime-types gems to compatible versions for Ruby < 2.0. I can alternatively update to drop support for 1.9 altogether - looks like this has been holding up quite a few PRs.
> Fix Travis, pin 1.9 dev dependencies

- lib/rack/tracker/google_tag_manager/template/google_tag_manager.erb
Variables pushed to the dataLayer after the container snippet are not registered. Moving the container to the last position.
> The dataLayer.push needs to occur before the container snippet

- lib/rack/tracker.rb
- lib/rack/tracker/google_tag_manager/google_tag_manager.rb
- lib/rack/tracker/google_tag_manager/template/google_tag_manager_body.erb
- lib/rack/tracker/google_tag_manager/template/google_tag_manager_head.erb
- lib/rack/tracker/handler.rb
- spec/handler/google_tag_manager_spec.rb
- spec/integration/google_tag_manager_integration_spec.rb
This allows handlers to define an #inject(response) method to directly manipulate the response html.
The google tag manager handler uses this to inject a snippet into the head and one snippet into the body (as required by google)
> Add support for different tracker locations for google tag manager

- README.md
- lib/rack/tracker/facebook_pixel/facebook_pixel.rb
- lib/rack/tracker/facebook_pixel/template/facebook_pixel.erb
- lib/rack/tracker/go_squared/go_squared.rb
- lib/rack/tracker/google_adwords_conversion/google_adwords_conversion.rb
- lib/rack/tracker/google_analytics/google_analytics.rb
- lib/rack/tracker/google_tag_manager/google_tag_manager.rb
- lib/rack/tracker/handler.rb
- lib/rack/tracker/zanox/zanox.rb
- spec/handler/facebook_pixel_spec.rb
- spec/integration/facebook_pixel_integration_spec.rb
- spec/support/metal_controller.rb
this should close: https://github.com/railslove/rack-tracker/issues/92
```
if you are not interested in tracking or optimizing for conversions,
you can pass custom event names into the trackCustom call.
```
https://developers.facebook.com/docs/ads-for-websites/pixel-events/v2.10#events
> Facebook pixel track custom

- lib/rack/tracker/facebook_pixel/facebook_pixel.rb
- lib/rack/tracker/facebook_pixel/template/facebook_pixel.erb
- lib/rack/tracker/google_analytics/google_analytics.rb
- lib/rack/tracker/handler.rb
- spec/handler/facebook_pixel_spec.rb
- spec/handler/google_analytics_spec.rb
- spec/handler/handler_spec.rb
This allows the Facebook Pixel id (as well as other tracker options) to be dynamic, and change on a per-request basis. It's based on some other trackers that offer this functionality (`:user_id` on the Google Analytics one, for example).
> Allow for dynamic Facebook Pixel options

- README.md
- lib/rack/tracker/google_analytics/template/google_analytics.erb
- spec/handler/google_analytics_spec.rb
Great gem. I used it today in a project, but had to use a custom handler to include the Google Optimize plugin into the Google Analytics snippet - as per [these instructions](https://support.google.com/360suite/optimize/answer/6262084#example-combined-snippet). It didn't feel like the best implementation, so I thought I'd add an option to the Google Analytics handler.
> Add option to pass Google Optimize container ID to Google Analytics

- lib/rack/tracker/google_tag_manager/google_tag_manager.rb
Change introduced in #86 causes issues with mismatches of closing brackets (single elements vs separately closed elements `<input/>` vs `<div></div>`) - removing the greediness cleanly matches *just* the `<body>` tag - regardless of what's contained in it.
You can see the problem with this behavior in rubular `<body.*>` vs `<body.*?>` - use the below HTML - the first without the question mark will return most (but not all!) of the HTML - with the question mark *just* the body tag is returned in the match.
sample HTML code used to repro issue:
```html
<html lang="en" style="font-size: 10px"><head></head><body class="app"><div class="portlet box blue" id=""><div class="portlet-title"><div class="tools"></div><div class="caption">Edit Location</div><div …
```
> Set wildcard to non-greedy for GTM body insertion

- lib/rack/tracker.rb
- spec/tracker/tracker_spec.rb
Following up with issue #105 (RuntimeError: string modified), this PR ensures that when the response string is frozen, `Rack::Tracker#inject` does not cause a `RuntimeError` and still works as before.
In addition to using frozen strings in the gem specs, I used this version of `rack-tracker` locally in our app (referred to by @jblock in #105). Tests that were previously failing because of [this change in Rails 5.2](https://github.com/rails/rails/pull/29933) are now passing.
Hopefully this is enough to resolve the issue!
> dup response string in Rack::Tracker#inject to avoid RuntimeError

- lib/rack/tracker/google_analytics/google_analytics.rb
- lib/rack/tracker/google_analytics/template/google_analytics.erb
- spec/handler/google_analytics_spec.rb
- spec/integration/google_analytics_integration_spec.rb
Hi, we use your gem in our project and we need to track (with google analytics) the hash part of the url in the pageview event. We found a solution in this stackoverflow thread : https://stackoverflow.com/a/4813223 .
I have simply added the option to the Google Analytics tracker for a custom pageview url script (which default to the old and normal url script).
I'm at your disposal if you need anything.
> Allow to use custom pageview url script for GoogleAnalytics tracker.

- README.md
I forgot to put some documentation in the README this in the previous PR (https://github.com/railslove/rack-tracker/pull/119) for the `pageview_url_script` option.
> Update README.md for Google Analytics option `pageview_url_script`.

- README.md
- lib/rack/tracker/google_global/google_global.rb
Adds the possibility to integrate Google Optimize ID into the allowed tracker options
> adds optimize_id to allowed tracker options

- README.md
- lib/rack/tracker.rb
- lib/rack/tracker/hubspot/hubspot.rb
- lib/rack/tracker/hubspot/template/hubspot.erb
- lib/rack/tracker/version.rb
- spec/handler/hubspot_spec.rb
- spec/integration/hubspot_integration_spec.rb
- spec/support/metal_controller.rb
First off, this package does a great job of consolidating the various trackers out there. For work, we need most of the things in here, along with Hubspot and a few others (PRs likely forthcoming). This specific change adds the Hubspot tracking code, as suggested in [their docuemntation](https://knowledge.hubspot.com/articles/kcs_article/reports/install-the-hubspot-tracking-code).
> Add Hubspot integration

- lib/rack/tracker/google_global/google_global.rb
- spec/handler/google_global_spec.rb
As agreed in #137 - made the change which will pass all the given attributes to the `gtag`.
It will only skip the `action` attribute, as that is used as a second argument already.
Please, would be awesome if you can merge this.
Thanks!
> #137: Accepting all passed attributes for google_global tracking

- README.md
- lib/rack/tracker.rb
- lib/rack/tracker/drift/drift.rb
- lib/rack/tracker/drift/template/drift.erb
- spec/handler/drift_spec.rb
- spec/integration/drift_integration_spec.rb
- spec/support/metal_controller.rb
Add Drift tracking snippet per [their installation docs](https://gethelp.drift.com/hc/en-us/articles/360019349154-Install-Drift-on-Your-Website-Using-the-Javascript-Snippet).
> Add support for Drift

- lib/rack/tracker/drift/template/drift.erb
- spec/integration/drift_integration_spec.rb
Fixes issue with https://github.com/railslove/rack-tracker/pull/139
Thank you in advance!
> Uncaught ReferenceError Fix: wrap Drift account ID in quotes

- CHANGELOG.md
- README.md
- lib/rack/tracker/google_analytics/google_analytics.rb
- lib/rack/tracker/google_analytics/template/google_analytics.erb
- lib/rack/tracker/version.rb
- spec/handler/google_analytics_spec.rb
My colleague @gasi recently noticed that our site was both sending GA's standard `pageview` event, as well as submitting a separate `Page/view` event. We aren't particularly interested in sending the explicit `pageview`s, so I've added an override that allows callers to disable it.
The default is to still send the explicit `pageview` though, so this is backwards compatible.
> Allow disabling explicit pageview sends for GA

- .travis.yml
- Gemfile.rails-6.0
also: [rails 3.2 is eol](https://guides.rubyonrails.org/maintenance_policy.html). should probably be dropped. will reduce ci time.
> test on rails 6.0

- README.md
- lib/rack/tracker.rb
- lib/rack/tracker/heap/heap.rb
- lib/rack/tracker/heap/template/heap.erb
- lib/rack/tracker/version.rb
- spec/handler/heap_spec.rb
- spec/integration/heap_integration_spec.rb
- spec/support/metal_controller.rb
This PR adds support for Heap.
I made an assumption about what the version would be - please let me know if it should be something else.
> Add support for Heap

- lib/rack/tracker/google_global/google_global.rb
- lib/rack/tracker/google_global/template/google_global.erb
- spec/integration/google_global_integration_spec.rb
i'm using the following code:
```rb
use Rack::Tracker do
handler :google_global, trackers: [ { id: ENV["GA_ID"] } ], anonymize_ip: true
end
```
which throws up the following way if `GA_ID` is empty:
```
NoMethodError:
undefined method `[]' for nil:NilClass
```
this patch properly handles the case of empty trackers in the templates and deals with a few other cases which should be considered "empty". also caches collected trackers in an ivar to save a few iterations and cleans up the integration test a little.
> google global: better empty tracker handling

- lib/rack/tracker.rb
We've noticed that in high traffic threaded environment (Puma) this middleware shares instance variables memory between threads and occasionally swaps ivars content.
In a worst-case scenario observed for a request from user A the response that was coming back was from a request made by a user B. If `Set-Cookie` header was present user A was immediately logged out and logged in as a user B (completely confusing users).
We've observed also a number of other requests/responses swaps which in general were hard to debug e.g. API request calls returning non-API responses.
This PR does not remove using of ivars (`@status`, `@headers`, `@body`) but rather duplicates the middleware calls. We are using forked repo for a few days now and we do not observe the issue anymore.
For more issues similar …
> Make middleware thread safe

- lib/rack/tracker.rb
see: https://github.com/railslove/rack-tracker/pull/150
> Use local variables in rack middleware to prevent instance state changes

- lib/rack/tracker/google_tag_manager/google_tag_manager.rb
- spec/handler/google_tag_manager_spec.rb
If the response html has no new line after `<head>` tag,
the gtm script tag will be placed on a bad place.
In case response html is
```
<html><head></head><body></body></html>
```
Then the response after `GoogleTagManager#inject` is being:
```
<html><head></head><body><noscript><iframe src="https://www.googletagmanager.com/ns.html?id=somebody"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
</body></html>
<script>
(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','somebody');</script> …
```
> Use leftmost match for gtm tag injection

- lib/rack/tracker/google_tag_manager/template/google_tag_manager_head.erb
- spec/integration/google_tag_manager_integration_spec.rb
This PR adds support for the new `turbo-rails` gem that supersedes `turbolinks`. It observes both turbo and turbolinks events.
Also, this PR fixes issue with multiple event listeners tracking stale events and duplicate page views. Since turbo (and turbolinks) are evaluating new scripts from the `head` element, it ends up registering a duplicate event listener any time a new event is pushed from the backend. This PR fixes that by generating a static script with the turbo event listener (it will be evaluated only once) and a dynamic script with backend events (its going be evaluated on every load if any events are present).
> hotwired/turbo support and fixes issue with duplicate events in GTM
